### ISSUE TITLE
How can I get data csv files? 

### ISSUE THREAD

**Issue by dilipbobby** [jldbc/gutenberg#17]
on Running TFIDF clustering code on preprocessed folder does it gives me the exact csv file with all  columns and rows like cluster size values(small,medium.large) etc values just like that are in git repo data folder ?

**Comment by jldbc** [comment]
The TF-IDF clustering code does TF-IDF clustering on the TF-IDF scores of the raw text. This requires you to first fetch and preprocess the text from Project Gutenberg. You will have to fetch the raw text data yourself, however, as is outlined in the README.
