### ISSUE TITLE
Comma and backslash issue in book names

### ISSUE THREAD

**Issue by jldbc** [jldbc/gutenberg#5]
tf-idf script is splitting book titles on commas, and this is causing it to break. Quick fix from earlier was to remove commas from book titles, but this is not going to work as we start taking titles from online. The backslash character is also causing it to break. 

e.g. "Lincoln's Gettysburg address, delivered in 1863" (one title)  => "Lincoln's Gettysburg address" and "delivered in 1863" as two separate titles,  where neither of these partial titles exist

**Comment by hoodr** [comment]
As we read in books from online, all we need to do is read in the file and save it as something else. Shouldn't be terrible in terms of reformatting. It shouldn't be too hard

**Comment by jldbc** [comment]
Good call - forgot we'd get to control the names as we read them in in that case
